# Generated by Django 5.1.4 on 2024-12-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='No Title Provided', max_length=100),
        ),
    ]
